# General settings
title: Fahad's Site
email: me<at>fahadiqbal<dot>com
description: >
  I am a 
baseurl: ""
url: ""
twitter_username: soyFahad
github_username:  fahadiqbal1

# Site specific settings
date_format:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-gist
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
