title = "Fahad Iqbal"
baseURL = "https://fahadiqbal.com/"
languageCode = "en-us"
copyright = "© Fahad Iqbal 2021"
sectionPagesMenu = "main"
enableRobotsTXT= true
enableGitInfo = true

[author]
    name = "Fahad Iqbal"

[params]
    description = "Personal Site of Fahad Iqbal"
    subtitle = "The thoughts and ramblings of an internet stranger"

[sitemap]
    ChangeFreq = ""
    Filename = "sitemap.xml"
    Priority = "-1"